### PR TITLE
Remove `Utils.Misc.unsnoc`

### LINKED ISSUE #4: Redundant `unsnoc` in `Utils.Misc`
[`Utils.Misc.Vect.unsnoc`](https://github.com/octeep/idris2-tls/blob/951bef674c41f059d5ccddf568b45588b5dbceee/src/Utils/Misc.idr#L234) is no longer needed because of [this pull request](https://github.com/idris-lang/Idris2/pull/2471). Building idris2-tls gives this error now:
```
Error: While processing right hand side of unsnoc. Ambiguous elaboration. Possible results:
    Utils.Misc.Vect.unsnoc (y Data.Vect.(::) ys)
    Data.Vect.unsnoc (y Data.Vect.(::) ys)
```

I can open a pull request to remove it if the contributors agree.

### PR DESCRIPTION
**Pull request by andreiburdusa**
Fixes #4

### CODE REVIEW

**Comment by andreiburdusa** [comment]
It looks like the checks are using Idris2 commit 43c5b5263cf7dd6788291b73220d841660050407, where `unsnoc` is not yet defined in `Data.Vector`.

**Comment by ghost** [comment]
> It looks like the checks are using Idris2 commit 43c5b5263cf7dd6788291b73220d841660050407, where `unsnoc` is not yet defined in `Data.Vector`.

yep I am fixing the CI right now. Having some troubles with the dependencies.

**Comment by andreiburdusa** [comment]
> > It looks like the checks are using Idris2 commit 43c5b5263cf7dd6788291b73220d841660050407, where `unsnoc` is not yet defined in `Data.Vector`.
> 
> yep I am fixing the CI right now. Having some troubles with the dependencies.

Oh, then should I not have pushed the last commit? I tried to update the Idris2 version

**Comment by ghost** [comment]
> > > It looks like the checks are using Idris2 commit 43c5b5263cf7dd6788291b73220d841660050407, where `unsnoc` is not yet defined in `Data.Vector`.
> > 
> > 
> > yep I am fixing the CI right now. Having some troubles with the dependencies.
> 
> Oh, then should I not have pushed the last commit? I tried to update the Idris2 version

Yeah you should retract it. I will merge your PR after I've fixed the CI.

**Pull request merged**
